seed_everything: 42

data:
  class_path: anomalib.data.MVTec
  init_args:
    root: ./datasets/MVTec
    category: bottle
    image_size: [256, 256]
    train_batch_size: 32
    test_batch_size: 32
    num_workers: 8

tiling:
  enable: false
  tile_size: 256

model:
  class_path: anomalib.models.Cflow
  init_args:
    task: segmentation
    adaptive_threshold: true
    default_image_threshold: 0
    default_pixel_threshold: 0
    input_size: [256, 256]
    backbone: resnet18
    layers:
      - layer1
      - layer2
      - layer3
    fiber_batch_size: 64
    decoder: freia-cflow
    condition_vector: 128
    coupling_blocks: 8
    clamp_alpha: 1.9
    permute_soft: true
    normalization: min_max # null | min_max | cdf
    # TODO: Learning rate should be placed under optimizer. Not in model.
    lr: 0.0001

trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 2
        monitor: pixel_AUROC
        mode: max
  accelerator: null
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  default_root_dir: null
  deterministic: false
  fast_dev_run: false
  gpus: 1
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 50
  max_steps: -1
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  replace_sampler_ddp: true
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0
  weights_save_path: null
  weights_summary: top
