seed_everything: 42
data:
  class_path: anomalib.data.MVTec
  init_args:
    root: ./datasets/MVTec
    category: bottle
    image_size: [32, 32]
    train_batch_size: 32
    test_batch_size: 32
    num_workers: 8

tiling:
  # TODO: Tiling is to be enabled for GANomaly to work properly.
  enable: true
  tile_size: 32

model:
  class_path: anomalib.models.Ganomaly
  init_args:
    task: classification
    adaptive_threshold: true
    default_image_threshold: 0.0
    default_pixel_threshold: 0.0
    input_size: [32, 32]
    # TODO Link batch_size with data.train_batch_size to avoid duplicate params.
    batch_size: 32
    latent_vec_size: 100
    n_features: 64
    extra_layers: 0
    add_final_conv_layer: true
    # TODO: Move optimizer parameters into optimizer section in config.yaml.
    lr: 0.0002
    beta1: 0.5
    beta2: 0.999
    wadv: 1
    wcon: 50
    wenc: 1
    normalization: null # null | min_max | cdf

trainer:
  callbacks: null
  accelerator: null
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 2
  checkpoint_callback: true
  default_root_dir: null
  deterministic: false
  fast_dev_run: false
  gpus: 1
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 100
  max_steps: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  replace_sampler_ddp: true
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0
  weights_save_path: null
  weights_summary: top
